"""Initial migration

Revision ID: 14c449dec3fa
Revises: 5f3aaee1740c
Create Date: 2026-02-06 14:27:12.282030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c449dec3fa'
down_revision = '5f3aaee1740c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

